###############
# Extra keys layout for Termux
###############

extra-keys = [ \
  [ \
    {key: 'ESC', popup: {macro: ':q ENTER', display: 'exit'}}, \
    {key: '/', popup: 'BACKSLASH'}, \
    {key: '-', popup: '_'}, \
    {key: 'HOME', popup: 'PGUP'}, \
    {key: 'UP'}, \
    {key: 'END', popup: 'PGDN'}, \
    {key: ':', popup: ';'}, \
    {key: '(', popup: '{'} \
  ], \
  [ \
    {key: 'TAB', popup: {macro: 'git status ENTER', display: 'git'}}, \
    {key: 'CTRL'}, \
    {key: 'ALT'}, \
    {key: 'LEFT'}, \
    {key: 'DOWN'}, \
    {key: 'RIGHT'}, \
    {key: '&', popup: '|'}, \
    {key: ')', popup: '}'} \
  ] \
]
